name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 07 * * FRI"

jobs:
  run:
    name: Run the CLI with ${{ matrix.shell }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        shell: [bash]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run CLI
        run: ${{ matrix.shell }} climax.sh
